### ISSUE TITLE
ValueError: `Checkpoint` was expecting a trackable object (an object derived from `TrackableBase`), got None.

### ISSUE THREAD

**Issue by chho-work** [dmolony3/SimCLR#1]
Hi,
Thanks for sharing your code!  Great work!

I tried to run "!python main.py --task=classification --cifar10=True --batch_size=256 --num_classes=10 --pretrain_save_path=logs/pretrain --finetune_save_path=logs/finetune --freeze" instruction in Colab using GPU. 

I got the following error message:
**********************************************************************************************************************************************
Loading CIFAR-10 model
2020-08-28 04:01:14.322279: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-08-28 04:01:14.377507: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-08-28 04:01:14.378125: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties: 
pciBusID: 0000:00:04.0 name: Tesla T4 computeCapability: 7.5
coreClock: 1.59GHz coreCount: 40 deviceMemorySize: 14.73GiB deviceMemoryBandwidth: 298.08GiB/s
2020-08-28 04:01:14.378428: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-08-28 04:01:14.605620: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2020-08-28 04:01:14.731693: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
2020-08-28 04:01:14.759917: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10
2020-08-28 04:01:15.033069: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10
2020-08-28 04:01:15.076131: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10
2020-08-28 04:01:15.599511: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-08-28 04:01:15.599773: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-08-28 04:01:15.600632: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-08-28 04:01:15.601384: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0
2020-08-28 04:01:15.601786: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-08-28 04:01:15.607637: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 2200000000 Hz
2020-08-28 04:01:15.607866: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x293ca00 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-08-28 04:01:15.607897: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-08-28 04:01:15.746968: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-08-28 04:01:15.747761: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x293cbc0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2020-08-28 04:01:15.747794: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Tesla T4, Compute Capability 7.5
2020-08-28 04:01:15.748574: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-08-28 04:01:15.749144: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties: 
pciBusID: 0000:00:04.0 name: Tesla T4 computeCapability: 7.5
coreClock: 1.59GHz coreCount: 40 deviceMemorySize: 14.73GiB deviceMemoryBandwidth: 298.08GiB/s
2020-08-28 04:01:15.749208: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-08-28 04:01:15.749234: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2020-08-28 04:01:15.749263: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
2020-08-28 04:01:15.749287: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10
2020-08-28 04:01:15.749307: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10
2020-08-28 04:01:15.749335: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10
2020-08-28 04:01:15.749361: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-08-28 04:01:15.749436: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-08-28 04:01:15.750057: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-08-28 04:01:15.750600: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0
2020-08-28 04:01:15.750663: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-08-28 04:01:15.754572: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-08-28 04:01:15.754617: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1108]      0 
2020-08-28 04:01:15.754630: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1121] 0:   N 
2020-08-28 04:01:15.754745: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-08-28 04:01:15.755343: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-08-28 04:01:15.755900: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:39] Overriding allow_growth setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.
2020-08-28 04:01:15.755940: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1247] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 14071 MB memory) -> physical GPU (device: 0, name: Tesla T4, pci bus id: 0000:00:04.0, compute capability: 7.5)
Fine-tuning model
Downloading data from https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz
170500096/170498071 [==============================] - 4s 0us/step
No checkpoint found in logs/pretrain, creating a new checkpoint manager
Traceback (most recent call last):
  File "main.py", line 106, in <module>
    run(config)
  File "main.py", line 41, in run
    finetune_cifar10(model, config)
  File "/content/SimCLR/simclr/finetune_cifar10.py", line 101, in finetune_cifar10
    checkpoint, manager = restore_weights(model, config.pretrain_save_path)
  File "/content/SimCLR/simclr/finetune_cifar10.py", line 186, in restore_weights
    checkpoint = tf.train.Checkpoint(step=tf.Variable(1), optimizer=optimizer, net=model)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/tracking/util.py", line 1818, in __init__
    % (v,))
ValueError: `Checkpoint` was expecting a trackable object (an object derived from `TrackableBase`), got None. If you believe this object should be trackable (i.e. it is part of the TensorFlow Python API and manages state), please open an issue.
*************************************************************************************************************************************************

My TF and TFAddons version:
TF ver: 2.2.0
TFAddons ver: 0.9.0

Can you pls help and indicate what I am doing wrong and how can I fix this?   

Many thanks!

**Comment by dmolony3** [comment]
I'm pretty sure this is because there are no saved checkpoints in the pretrained save path. I have pushed changes to the code to return an error if this is the case. Just to confirm did you pretrain a model prior to running the classification mode?

**Comment by chho-work** [comment]
Thanks for your prompt reply!  

I tried initially to use this command for pretraining:
"!python main.py --task=pretrain --cifar10=True --batch_size=256 --num_epochs=1000 --temperature=0.1 --strength=0.5 --learning_rate=1.0" for pretraining, but it returned an error(issue #1).  Now that I see you've made the change, I will try again.  

I believe with issue 1 solved, issue 2 won't be a problem.  Thanks for your help!
